package Interface;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.UserDirectory;
import Interface.ManageAirliners.ManageAirlinersJPanel;
import Interface.ManageCustomers.ManageCustomersJPanel;
import Interface.ManageTravelAgency.ManageTravelAgencyJPanel;
import Interface.ManageTravelAgency.TravelAgencyLoginJPanel;
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ajith
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private AirlinerDirectory airlineDirectory;
    private CustomerDirectory customerDirectory;
    private UserDirectory userDirectory;

    public MainFrame() {
        initComponents();
        airlineDirectory = new AirlinerDirectory();
        customerDirectory = new CustomerDirectory();
        userDirectory = new UserDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageTravelAgencyBtn = new javax.swing.JButton();
        manageCustomerBtn = new javax.swing.JButton();
        manageAirlinerBtn = new javax.swing.JButton();
        panelRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageTravelAgencyBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        manageTravelAgencyBtn.setText("Manage Travel Agency");
        manageTravelAgencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTravelAgencyBtnActionPerformed(evt);
            }
        });

        manageCustomerBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        manageCustomerBtn.setText("Manage Customers");
        manageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerBtnActionPerformed(evt);
            }
        });

        manageAirlinerBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageAirlinerBtn.setText("Manage Airliners");
        manageAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageTravelAgencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAirlinerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(manageTravelAgencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        panelRight.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(panelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelRight.getLayout();
        ManageCustomersJPanel manageCustomers = new ManageCustomersJPanel(panelRight, customerDirectory);
        panelRight.add("ManageCustomersJPanel", manageCustomers);
        layout.next(panelRight);
    }//GEN-LAST:event_manageCustomerBtnActionPerformed

    private void manageTravelAgencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTravelAgencyBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelRight.getLayout();
        TravelAgencyLoginJPanel loginTravelAgencyJPanel = new TravelAgencyLoginJPanel(panelRight, airlineDirectory, customerDirectory, userDirectory);
        panelRight.add("TravelAgencyLoginJPanel", loginTravelAgencyJPanel);
        layout.next(panelRight);
    }//GEN-LAST:event_manageTravelAgencyBtnActionPerformed

    private void manageAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panelRight.getLayout();
        ManageAirlinersJPanel manageAirlinePanel = new ManageAirlinersJPanel(panelRight, airlineDirectory, userDirectory);
        panelRight.add("ManageAirlinersJPanel", manageAirlinePanel);
        layout.next(panelRight);
    }//GEN-LAST:event_manageAirlinerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAirlinerBtn;
    private javax.swing.JButton manageCustomerBtn;
    private javax.swing.JButton manageTravelAgencyBtn;
    private javax.swing.JPanel panelRight;
    // End of variables declaration//GEN-END:variables
}
