/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirliners;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.UserAccount;
import Business.UserDirectory;
import Interface.ManageTravelAgency.CreateNewFlightScheduleJPanel;
import Interface.ManageTravelAgency.ViewFlightScheduleJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajith
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    private JPanel panelRight;
    private AirlinerDirectory airlinerDirectory;
    private Airliner airliner;
    private UserDirectory userDirectory;
    
    public ViewAirlinerJPanel(JPanel panelRight, AirlinerDirectory ad, Airliner airliner, UserDirectory userDirectory) {
        initComponents();
        this.airlinerDirectory = ad;
        this.panelRight = panelRight;
        this.airliner = airliner;
        this.userDirectory = userDirectory;
        flightScheduleJTable.setVisible(false);
        newFlightBtn.setVisible(false);
        viewFlightBtn.setVisible(false);
    }

    public void populateAirlinerDetails(){
        flightScheduleJTable.setVisible(true);
        newFlightBtn.setVisible(true);
        viewFlightBtn.setVisible(true);
         DefaultTableModel dtm = (DefaultTableModel)flightScheduleJTable.getModel();
         dtm.setRowCount(0);
            Object[] row = new Object[5];
            List<Airplane> flightFleet = airliner.getFlightFleet();
            for(int i=0; i<flightFleet.size();i++){
                Airplane airplane = flightFleet.get(i);
                row[0] = airplane;
                row[1] = airplane.getFlightSchedule();
                row[2] = airplane.getFromLocation();
                row[3] = airplane.getToLocation();
           dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameJText = new javax.swing.JTextField();
        passwordJText = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightScheduleJTable = new javax.swing.JTable();
        logoutBtn = new javax.swing.JButton();
        newFlightBtn = new javax.swing.JButton();
        viewFlightBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("View Airliner");

        jLabel2.setText("User Name:");

        jLabel3.setText("Password:");

        loginJButton.setText("Log In");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        flightScheduleJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Id", "Schedule Time", "From Location", "To Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightScheduleJTable);

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        newFlightBtn.setText("New Flight");
        newFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFlightBtnActionPerformed(evt);
            }
        });

        viewFlightBtn.setText("View Flight");
        viewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(loginJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(newFlightBtn)
                        .addGap(22, 22, 22)
                        .addComponent(viewFlightBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn)))
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginJButton)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFlightBtn)
                    .addComponent(viewFlightBtn)
                    .addComponent(logoutBtn))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
         int selectionButton = JOptionPane.YES_NO_OPTION;
         int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm logout?","Warning",selectionButton);
         if(selectionResult == JOptionPane.YES_OPTION){
              ManageAirlinersJPanel manageAirlinePanel = new ManageAirlinersJPanel(panelRight, airlinerDirectory,userDirectory);  
                panelRight.add("ManageAirlinersJPanel", manageAirlinePanel);
                layout.previous(panelRight);
            }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
        if(userNameJText.getText()==null || userNameJText.getText().equals("")){
            userNameJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel1.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Username cannot be empty");
            return;
     }
     if(passwordJText.getText()==null || passwordJText.getText().equals("")){
            passwordJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Password cannot be empty");
            return;
     }
     UserAccount userAccount =  userDirectory.authenticateUser(userNameJText.getText(),passwordJText.getText(),airliner.getAirlinerName(),"Airliner");
     if(userAccount==null){
          JOptionPane.showMessageDialog(null, "Invalid Credentials");
            return;
     }
     else{
        populateAirlinerDetails();
        userNameJText.setText("");
        passwordJText.setText("");
     }
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void newFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFlightBtnActionPerformed
        // TODO add your handling code here:
        CreateNewFlightScheduleJPanel createNewFlightJPanel = new CreateNewFlightScheduleJPanel(panelRight,airlinerDirectory,airliner.getAirlinerName(),userDirectory);
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add("CreateNewFlightScheduleJPanel", createNewFlightJPanel);
        layout.next(panelRight);
    }//GEN-LAST:event_newFlightBtnActionPerformed

    private void viewFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = flightScheduleJTable.getSelectedRow();
         
        if(selectedRow>=0){
            Airplane airplane = (Airplane)flightScheduleJTable.getValueAt(selectedRow, 0);
            ViewFlightScheduleJPanel viewFlightJPanel = new ViewFlightScheduleJPanel(panelRight,airlinerDirectory,airplane,airliner.getFlightFleet(),airliner,userDirectory);
            CardLayout layout = (CardLayout)panelRight.getLayout();
            panelRight.add("ViewFlightScheduleJPanel", viewFlightJPanel);
            layout.next(panelRight);
         }
    }//GEN-LAST:event_viewFlightBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)panelRight.getLayout();
        ManageAirlinersJPanel manageAirlinePanel = new ManageAirlinersJPanel(panelRight, airlinerDirectory,userDirectory);
        panelRight.add("ManageAirlinersJPanel", manageAirlinePanel);
        layout.next(panelRight);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable flightScheduleJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton newFlightBtn;
    private javax.swing.JTextField passwordJText;
    private javax.swing.JTextField userNameJText;
    private javax.swing.JButton viewFlightBtn;
    // End of variables declaration//GEN-END:variables
}
