/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.DemographicInfo;
import Business.AddressInfo;
import Business.DriverLicenseInfo;
import Business.SavingAccountInfo;
import Business.CheckingAccountInfo;
import Business.MedicalRecord;
import Business.CreateProfile;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author wase.a
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private CreateProfile createProfile;
    
    private DemographicInfo demographicInfo;
    private AddressInfo addressInfo;
    private DriverLicenseInfo driverLicenseInfo;
    private SavingAccountInfo savingAccountInfo;
    private CheckingAccountInfo checkingAccountInfo;
    private MedicalRecord medicalRecord;
    
    public CreateJPanel(CreateProfile createProfile) {
        initComponents();
        this.createProfile=createProfile;
        
        demographicInfo = new DemographicInfo();
        addressInfo = new AddressInfo();
        savingAccountInfo = new SavingAccountInfo();
        checkingAccountInfo = new CheckingAccountInfo();
        driverLicenseInfo = new DriverLicenseInfo();
        medicalRecord = new MedicalRecord();      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DemographicInformationJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateOfBirthTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        AddressInformationJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        streetAddressTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        BankInformationJPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        accountTypeTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        accountNoTextField = new javax.swing.JTextField();
        routingNoTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        accountBalanceTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bankName2TextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        accountType2TextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        accountNo2TextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        routingNo2TextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        accountBalance2TextField = new javax.swing.JTextField();
        DriverInformationJPanel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        licenseNumberTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        dateOfIssueTextField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        dateOfExpirationTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        bloodTypeTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        MedicalRecordJPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        medicalRecordNumberTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        alergy1TextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        alergy2TextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        alergy3TextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(245, 249, 254));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setForeground(new java.awt.Color(243, 244, 255));
        setPreferredSize(new java.awt.Dimension(800, 750));

        CreateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(0, 52, 161));
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(245, 249, 254));

        jLabel1.setBackground(new java.awt.Color(245, 249, 254));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 52, 161));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a Profile");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DemographicInformationJPanel.setBackground(new java.awt.Color(245, 249, 254));
        DemographicInformationJPanel.setForeground(new java.awt.Color(38, 131, 249));
        DemographicInformationJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DemographicInformationJPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 52, 161));
        jLabel2.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(0, 52, 161));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 52, 161));
        jLabel5.setText("Date of Birth");

        dateOfBirthTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dateOfBirthTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 52, 161));
        jLabel8.setText("Weight");

        weightTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        weightTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 161));
        jLabel3.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 52, 161));
        jLabel6.setText("Age");

        lastNameTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(0, 52, 161));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 52, 161));
        jLabel4.setText("Phone Number");

        phoneNumberTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        phoneNumberTextField.setForeground(new java.awt.Color(0, 52, 161));
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        ageTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ageTextField.setForeground(new java.awt.Color(0, 52, 161));
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 52, 161));
        jLabel7.setText("Height");

        heightTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        heightTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 52, 161));
        jLabel9.setText("Social Security Number");

        ssnTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ssnTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 52, 161));
        jLabel10.setText("Demographic Information");

        javax.swing.GroupLayout DemographicInformationJPanelLayout = new javax.swing.GroupLayout(DemographicInformationJPanel);
        DemographicInformationJPanel.setLayout(DemographicInformationJPanelLayout);
        DemographicInformationJPanelLayout.setHorizontalGroup(
            DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                        .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                                .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                                        .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastNameTextField)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DemographicInformationJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(heightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(phoneNumberTextField))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DemographicInformationJPanelLayout.setVerticalGroup(
            DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemographicInformationJPanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DemographicInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        AddressInformationJPanel.setBackground(new java.awt.Color(245, 249, 254));
        AddressInformationJPanel.setForeground(new java.awt.Color(0, 52, 161));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 52, 161));
        jLabel11.setText("Address Information");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 52, 161));
        jLabel12.setText("Street Address");

        streetAddressTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        streetAddressTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 52, 161));
        jLabel13.setText("City");

        cityTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cityTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 52, 161));
        jLabel14.setText("State");

        stateTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 52, 161));
        jLabel15.setText(" Zip Code");

        zipCodeTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        zipCodeTextField.setForeground(new java.awt.Color(0, 52, 161));
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddressInformationJPanelLayout = new javax.swing.GroupLayout(AddressInformationJPanel);
        AddressInformationJPanel.setLayout(AddressInformationJPanelLayout);
        AddressInformationJPanelLayout.setHorizontalGroup(
            AddressInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressInformationJPanelLayout.createSequentialGroup()
                .addGroup(AddressInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(AddressInformationJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddressInformationJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(streetAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddressInformationJPanelLayout.setVerticalGroup(
            AddressInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressInformationJPanelLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(streetAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BankInformationJPanel.setBackground(new java.awt.Color(245, 249, 254));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 52, 161));
        jLabel16.setText("Bank Account Information");

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 52, 161));
        jLabel38.setText("1st Bank Account");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 52, 161));
        jLabel17.setText("Bank Name");

        bankNameTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bankNameTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 52, 161));
        jLabel20.setText("Routing Number");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 52, 161));
        jLabel18.setText("Account Type");

        accountTypeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountTypeTextField.setForeground(new java.awt.Color(0, 52, 161));
        accountTypeTextField.setText("Savings");
        accountTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeTextFieldActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 52, 161));
        jLabel19.setText("Account Number");

        accountNoTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        accountNoTextField.setForeground(new java.awt.Color(0, 52, 161));

        routingNoTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        routingNoTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 52, 161));
        jLabel21.setText("Account Balance");

        accountBalanceTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        accountBalanceTextField.setForeground(new java.awt.Color(0, 52, 161));
        accountBalanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceTextFieldActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 52, 161));
        jLabel39.setText("2nd Bank Account");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 52, 161));
        jLabel23.setText("Bank Name");

        bankName2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bankName2TextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 52, 161));
        jLabel24.setText("Account Type");

        accountType2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        accountType2TextField.setForeground(new java.awt.Color(0, 52, 161));
        accountType2TextField.setText("Checking");
        accountType2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountType2TextFieldActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 52, 161));
        jLabel25.setText("Account Number");

        accountNo2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        accountNo2TextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 52, 161));
        jLabel26.setText("Routing Number");

        routingNo2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        routingNo2TextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 52, 161));
        jLabel27.setText("Account Balance");

        accountBalance2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        accountBalance2TextField.setForeground(new java.awt.Color(0, 52, 161));

        javax.swing.GroupLayout BankInformationJPanelLayout = new javax.swing.GroupLayout(BankInformationJPanel);
        BankInformationJPanel.setLayout(BankInformationJPanelLayout);
        BankInformationJPanelLayout.setHorizontalGroup(
            BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39)
            .addGroup(BankInformationJPanelLayout.createSequentialGroup()
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankInformationJPanelLayout.createSequentialGroup()
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(routingNoTextField)))
                    .addGroup(BankInformationJPanelLayout.createSequentialGroup()
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankName2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routingNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BankInformationJPanelLayout.createSequentialGroup()
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(accountBalanceTextField))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BankInformationJPanelLayout.createSequentialGroup()
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountBalance2TextField)
                            .addComponent(accountType2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(accountNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLabel16)
            .addComponent(jLabel38)
        );
        BankInformationJPanelLayout.setVerticalGroup(
            BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankInformationJPanelLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(accountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(routingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(accountBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BankInformationJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bankName2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(accountType2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(accountNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BankInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(routingNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(accountBalance2TextField))
                .addContainerGap())
        );

        DriverInformationJPanel.setBackground(new java.awt.Color(245, 249, 254));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 52, 161));
        jLabel28.setText("Driver License Information");

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 52, 161));
        jLabel29.setText("License Number");

        licenseNumberTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        licenseNumberTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 52, 161));
        jLabel30.setText("Date of Issue");

        dateOfIssueTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dateOfIssueTextField.setForeground(new java.awt.Color(0, 52, 161));
        dateOfIssueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfIssueTextFieldActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 52, 161));
        jLabel31.setText("Date of Expiration");

        dateOfExpirationTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dateOfExpirationTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 52, 161));
        jLabel32.setText("Blood Type");

        bloodTypeTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bloodTypeTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 52, 161));
        jLabel40.setText("Driver License");

        jButton1.setText("Upload Driving License");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DriverInformationJPanelLayout = new javax.swing.GroupLayout(DriverInformationJPanel);
        DriverInformationJPanel.setLayout(DriverInformationJPanelLayout);
        DriverInformationJPanelLayout.setHorizontalGroup(
            DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DriverInformationJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriverInformationJPanelLayout.createSequentialGroup()
                        .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30))
                        .addGap(33, 33, 33)
                        .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(DriverInformationJPanelLayout.createSequentialGroup()
                                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(509, 509, 509))
                                .addGroup(DriverInformationJPanelLayout.createSequentialGroup()
                                    .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel40)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1)
                                    .addGap(84, 84, 84)))))
                    .addGroup(DriverInformationJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(dateOfExpirationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28)))
        );
        DriverInformationJPanelLayout.setVerticalGroup(
            DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverInformationJPanelLayout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(dateOfIssueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DriverInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(dateOfExpirationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MedicalRecordJPanel.setBackground(new java.awt.Color(245, 249, 254));

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 52, 161));
        jLabel33.setText("Medical Record");

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 52, 161));
        jLabel34.setText("Medical Record Number");

        medicalRecordNumberTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        medicalRecordNumberTextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel35.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 52, 161));
        jLabel35.setText("Alergy 1");

        alergy1TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alergy1TextField.setForeground(new java.awt.Color(0, 52, 161));

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 52, 161));
        jLabel36.setText("Alergy 2");

        alergy2TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alergy2TextField.setForeground(new java.awt.Color(0, 52, 161));
        alergy2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy2TextFieldActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 52, 161));
        jLabel37.setText("Alergy 3");

        alergy3TextField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alergy3TextField.setForeground(new java.awt.Color(0, 52, 161));

        javax.swing.GroupLayout MedicalRecordJPanelLayout = new javax.swing.GroupLayout(MedicalRecordJPanel);
        MedicalRecordJPanel.setLayout(MedicalRecordJPanelLayout);
        MedicalRecordJPanelLayout.setHorizontalGroup(
            MedicalRecordJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalRecordJPanelLayout.createSequentialGroup()
                .addGroup(MedicalRecordJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(MedicalRecordJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(medicalRecordNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MedicalRecordJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(alergy1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(alergy2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(alergy3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MedicalRecordJPanelLayout.setVerticalGroup(
            MedicalRecordJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalRecordJPanelLayout.createSequentialGroup()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MedicalRecordJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(medicalRecordNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MedicalRecordJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(alergy1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(alergy2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(alergy3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(CreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DriverInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DemographicInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddressInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BankInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MedicalRecordJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator7)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(DemographicInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(AddressInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BankInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DriverInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalRecordJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        demographicInfo.setFirstName(firstNameTextField.getText());
        demographicInfo.setLastName(lastNameTextField.getText());
        demographicInfo.setPhoneNumber(phoneNumberTextField.getText());
        demographicInfo.setDateOfBirth(dateOfBirthTextField.getText());
        demographicInfo.setAge(ageTextField.getText());
        demographicInfo.setHeight(heightTextField.getText());
        demographicInfo.setWeight(weightTextField.getText());
        demographicInfo.setSSN(ssnTextField.getText());
        
        addressInfo.setStreetAddress(streetAddressTextField.getText());
        addressInfo.setCity(cityTextField.getText());
        addressInfo.setState(stateTextField.getText());
        addressInfo.setZipCode(zipCodeTextField.getText());
        
        savingAccountInfo.setBankName(bankNameTextField.getText());
        savingAccountInfo.setAccountType(accountTypeTextField.getText());
        savingAccountInfo.setBankAccountNumber(accountNoTextField.getText());
        savingAccountInfo.setBankRoutingNumber(routingNoTextField.getText());
        savingAccountInfo.setAccountBalance(accountBalanceTextField.getText());
        
        checkingAccountInfo.setBankName(bankName2TextField.getText());
        checkingAccountInfo.setAccountType(accountType2TextField.getText());
        checkingAccountInfo.setBankAccountNumber(accountNo2TextField.getText());
        checkingAccountInfo.setBankRoutingNumber(routingNo2TextField.getText());
        checkingAccountInfo.setAccountBalance(accountBalance2TextField.getText());
        
        driverLicenseInfo.setLicenseNumber(licenseNumberTextField.getText());
        driverLicenseInfo.setDateOfIssue(dateOfIssueTextField.getText());
        driverLicenseInfo.setDateOfExpiration(dateOfExpirationTextField.getText());
        driverLicenseInfo.setBloodType(bloodTypeTextField.getText());
        //driverLicenseInfo.setPhotoIdLocation(TOOL_TIP_TEXT_KEY);
        
        medicalRecord.setMedicalRecordNumber(medicalRecordNumberTextField.getText());
        medicalRecord.setAlergy1(alergy1TextField.getText());
        medicalRecord.setAlergy2(alergy2TextField.getText());
        medicalRecord.setAlergy3(alergy3TextField.getText());
        
        
        createProfile.setDemographicInfo(demographicInfo);
        createProfile.setAddressInfo(addressInfo);
        createProfile.setSavingAccountInfo(savingAccountInfo);
        createProfile.setCheckingAccountInfo(checkingAccountInfo);
        createProfile.setDriverLicenseInfo(driverLicenseInfo);
        createProfile.setMedicalRecord(medicalRecord);
        
      
        
        JOptionPane.showMessageDialog(null, "Profile Created Successfully");
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void accountType2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountType2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountType2TextFieldActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void accountBalanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void accountTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeTextFieldActionPerformed

    private void dateOfIssueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfIssueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfIssueTextFieldActionPerformed

    private void alergy2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy2TextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jFileChooser=new JFileChooser();
        jFileChooser.showSaveDialog(null);
        
        //jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         driverLicenseInfo.setPhotoIdLocation(jFileChooser.getSelectedFile().getAbsolutePath());
         
         JOptionPane.showMessageDialog(null, "Image Uploaded Successfully!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressInformationJPanel;
    private javax.swing.JPanel BankInformationJPanel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JPanel DemographicInformationJPanel;
    private javax.swing.JPanel DriverInformationJPanel;
    private javax.swing.JPanel MedicalRecordJPanel;
    private javax.swing.JTextField accountBalance2TextField;
    private javax.swing.JTextField accountBalanceTextField;
    private javax.swing.JTextField accountNo2TextField;
    private javax.swing.JTextField accountNoTextField;
    private javax.swing.JTextField accountType2TextField;
    private javax.swing.JTextField accountTypeTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField alergy1TextField;
    private javax.swing.JTextField alergy2TextField;
    private javax.swing.JTextField alergy3TextField;
    private javax.swing.JTextField bankName2TextField;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JTextField dateOfExpirationTextField;
    private javax.swing.JTextField dateOfIssueTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField licenseNumberTextField;
    private javax.swing.JTextField medicalRecordNumberTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField routingNo2TextField;
    private javax.swing.JTextField routingNoTextField;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetAddressTextField;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
